# SPDX-License-Identifier: MIT

from pathlib import Path
import importlib.util
import os
import subprocess
import sys
import tempfile
from typing import Any, cast
import unittest


ROOT = Path(__file__).resolve().parent.parent


class GeneratedBarTest(unittest.TestCase):
    def test_generated_contract(self) -> None:
        bar = (ROOT / "Bar.qml").read_text(encoding="utf-8")
        self.assertTrue(bar.startswith("// GENERATED by tools/sync_stock_bar.py"))
        self.assertIn("// SPDX-License-Identifier: MIT", bar[:300])
        self.assertIn("// Derived from Omarchy, Copyright (c) David Heinemeier Hansson.", bar[:300])
        self.assertIn('import "MonitorBarModel.js" as MonitorBarModel', bar)
        self.assertIn('mode: "hidden"', bar)
        self.assertIn('monitorSpec.mode !== "hidden"', bar)
        self.assertIn('root.isPrimaryScreen(slot.screenName)', bar)
        self.assertNotIn('screenName === "DP-1"', bar)
        self.assertNotIn('screenName !== "DP-1"', bar)
        self.assertIn("MonitorBarModel.configFromShell(\n      shell && shell.shellConfig ? shell.shellConfig : ({}),\n      connectedMonitorNames()", bar)
        self.assertIn("function onScreensChanged() { root.applyBarConfig() }", bar)
        self.assertIn("WlrLayershell.keyboardFocus: WlrKeyboardFocus.None", bar)

        model = (ROOT / "BarModel.js").read_text(encoding="utf-8")
        self.assertTrue(model.startswith("// GENERATED by tools/sync_stock_bar.py"))
        self.assertIn("// SPDX-License-Identifier: MIT", model[:300])
        self.assertIn("// Derived from Omarchy, Copyright (c) David Heinemeier Hansson.", model[:300])

    def test_assets_resolve_from_manifest_source_dir(self) -> None:
        bar = (ROOT / "Bar.qml").read_text(encoding="utf-8")
        self.assertIn("manifest && manifest.__sourceDir", bar)
        self.assertIn('monitorAssetSource("MonitorGlyph.qml")', bar)
        self.assertIn('monitorAssetSource("Workspaces.qml")', bar)
        self.assertIn('monitorAssetSource("SettingsButton.qml")', bar)
        self.assertIn("onManifestChanged:", bar)
        self.assertNotIn("/plugins/patrickfanella.monitor-bar", bar)

    def test_synthetic_workspace_id_is_unique(self) -> None:
        bar = (ROOT / "Bar.qml").read_text(encoding="utf-8")
        self.assertIn('entry.id = "patrickfanella.monitor-workspaces"', bar)
        self.assertIn('entry.workspaceIds = []', bar)
        self.assertIn('function fullWorkspaceEntry(sourceEntry)', bar)
        self.assertIn('delete entry.workspaceIds', bar)
        self.assertIn('entryId(entries[i]) === "omarchy.workspaces"', bar)

    def test_settings_button_is_runtime_only(self) -> None:
        bar = (ROOT / "Bar.qml").read_text(encoding="utf-8")
        self.assertIn('id: "patrickfanella.monitor-bar.settings"', bar)
        self.assertIn('syntheticSettings: true', bar)
        self.assertIn('!(entry && entry.syntheticSettings)', bar)
        self.assertIn('if (isPrimaryScreen(screenName))', bar)

    def test_generation_preserves_modes_and_noop_content(self) -> None:
        spec = cast(Any, importlib.util.spec_from_file_location(
            "sync_stock_bar", ROOT / "tools" / "sync_stock_bar.py"
        ))
        module = cast(Any, importlib.util.module_from_spec(spec))
        spec.loader.exec_module(module)
        with tempfile.TemporaryDirectory() as temporary:
            module.PLUGIN_DIR = Path(temporary)
            bar = module.PLUGIN_DIR / "Bar.qml"
            model = module.PLUGIN_DIR / "BarModel.js"
            bar.write_text("old", encoding="utf-8")
            model.write_text("old", encoding="utf-8")
            bar.chmod(0o640)
            model.chmod(0o600)
            outputs = {
                "Bar.qml": module.GENERATED_MARKER + "bar\n",
                "BarModel.js": module.GENERATED_MARKER + "model\n",
            }
            module.replace_generated(outputs)
            self.assertEqual(os.stat(bar).st_mode & 0o777, 0o640)
            self.assertEqual(os.stat(model).st_mode & 0o777, 0o600)
            before = (bar.stat().st_mtime_ns, model.stat().st_mtime_ns)
            module.replace_generated(outputs)
            self.assertEqual(before, (bar.stat().st_mtime_ns, model.stat().st_mtime_ns))

    def test_fixture_upstream_dir_generates_current_files(self) -> None:
        result = subprocess.run(
            [
                sys.executable,
                str(ROOT / "tools" / "sync_stock_bar.py"),
                "--upstream-dir",
                str(ROOT / "vendor" / "omarchy-4.0.1-1" / "bar"),
                "--check",
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_settings_preserve_screen_order_for_bootstrap_only(self) -> None:
        settings = (ROOT / "SettingsPanel.qml").read_text(encoding="utf-8")
        connected = settings[settings.index("  function connectedNames() {"):settings.index("  function isConnected")]
        refresh = settings[settings.index("  function refreshMonitors() {"):settings.index("  function ensureSelectedOutput")]
        self.assertNotIn("sort()", connected)
        self.assertIn("names.sort()", refresh)

    def test_keyboard_contracts_are_present(self) -> None:
        settings = (ROOT / "SettingsPanel.qml").read_text(encoding="utf-8")
        self.assertIn("readonly property bool modalOpen: closeConfirmOpen || restartArmed", settings)
        self.assertIn("enabled: !root.modalOpen", settings)
        self.assertIn("KeyNavigation.tab: discardCloseButton", settings)
        self.assertIn("KeyNavigation.tab: cancelCloseButton", settings)
        self.assertIn("function focusWorkspaceControl(index, control)", settings)
        self.assertIn("function ensureFocusedVisible(item)", settings)
        self.assertNotIn("onActiveFocusItemChanged", settings)
        self.assertIn("onActiveFocusChanged: if (activeFocus) root.ensureFocusedVisible(workspaceIdField)", settings)
        self.assertIn('Accessible.role: Accessible.Dialog', settings)

        settings_button = (ROOT / "SettingsButton.qml").read_text(encoding="utf-8")
        self.assertIn("activeFocusOnTab: true", settings_button)
        self.assertIn("if (!event.isAutoRepeat) root.activate()", settings_button)

        workspaces = (ROOT / "Workspaces.qml").read_text(encoding="utf-8")
        self.assertIn("Accessible.selected: focused", workspaces)
        self.assertNotIn("activeFocusOnTab: true", workspaces)


if __name__ == "__main__":
    unittest.main()
