#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Vendor Omarchy's stock bar and apply monitor-layout transforms."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import stat
import sys
import tempfile


UPSTREAM_DIR = Path("/usr/share/omarchy/shell/plugins/bar")
PLUGIN_DIR = Path(__file__).resolve().parent.parent
EXPECTED_SHA256 = {
    "Bar.qml": "a9db2da058c2822dd0f47547f5fb4b07252de91c75445874e4ef39e0e2779786",
    "BarModel.js": "908f30edce60dcba46d2039ba3d501fd0faa35fa1f90b7dbda69439288f8a8d0",
}
GENERATED_MARKER = """// GENERATED by tools/sync_stock_bar.py from Omarchy stock sources. DO NOT EDIT.
// SPDX-License-Identifier: MIT
// Derived from Omarchy, Copyright (c) David Heinemeier Hansson.
"""


def replace_exact(text: str, old: str, new: str, *, count: int = 1) -> str:
    actual = text.count(old)
    if actual != count:
        raise RuntimeError(
            f"expected {count} occurrence(s), found {actual}: {old.splitlines()[0]!r}"
        )
    return text.replace(old, new)


def transform_bar(source: str) -> str:
    text = source
    text = replace_exact(
        text,
        'import "BarModel.js" as BarModel\n',
        'import "BarModel.js" as BarModel\nimport "MonitorBarModel.js" as MonitorBarModel\n',
    )
    text = replace_exact(
        text,
        """  // The omarchy-shell host injects omarchyPath from OMARCHY_PATH.
  required property string omarchyPath
  // Injected by the host shell so bar slots can resolve enabled widgets.
  required property var barWidgetRegistry
  // Injected by the host shell every time shell.json is reloaded. Holds the
  // `bar:` subtree: position, centerAnchor, layout. The host owns file IO;
  // the bar just renders whatever it's handed. The bar font follows the
  // OS-level fontconfig monospace binding — it is not stored in shell.json.
  required property var barConfig
  // Injected by the host shell. Used for shell-wide actions such as opening
  // settings and persisting inline widget state.
  property var shell: null
  // Manifest for the active bar option. Present for custom bars and useful for
  // diagnostics; the built-in bar does not otherwise need it.
  property var manifest: null
""",
        """  // Custom bars are loaded asynchronously, then receive host properties.
  property string omarchyPath: ""
  property var barWidgetRegistry: null
  property var barConfig: ({})
  property var shell: null
  property var manifest: null
  property var monitorConfig: MonitorBarModel.defaultConfig([])
  property string monitorConfigText: ""
""",
    )
    text = replace_exact(
        text,
        """    var next = normalizeLayout(config.layout)
    var delta = BarModel.inlineSettingsDelta(layoutConfig, next)
    if (delta) {
      applySettingsDelta(delta)
      return
    }
    layoutConfig = next
    barConfigSerial++
""",
        """    var nextMonitorConfig = MonitorBarModel.configFromShell(
      shell && shell.shellConfig ? shell.shellConfig : ({}),
      connectedMonitorNames()
    )
    var nextMonitorConfigText = MonitorBarModel.serializeConfig(nextMonitorConfig)
    var monitorChanged = nextMonitorConfigText !== monitorConfigText
    if (monitorChanged) {
      monitorConfig = nextMonitorConfig
      monitorConfigText = nextMonitorConfigText
    }

    var next = normalizeLayout(config.layout)
    var delta = BarModel.inlineSettingsDelta(layoutConfig, next)
    if (delta) {
      applySettingsDelta(delta)
      if (monitorChanged) barConfigSerial++
      return
    }
    layoutConfig = next
    barConfigSerial++
""",
    )
    text = replace_exact(
        text,
        """  function customModuleSource(entry) {
    var source = BarModel.customModulePath(entry, home, omarchyConfigDir)
    return source ? Util.fileUrl(source) : ""
  }
""",
        """  function customModuleSource(entry) {
    var source = BarModel.customModulePath(entry, home, omarchyConfigDir)
    return source ? Util.fileUrl(source) : ""
  }

  // --- patrickfanella.monitor-bar: screen-local synthetic layouts ---
  readonly property string monitorAssetDir: manifest && manifest.__sourceDir ? String(manifest.__sourceDir) : ""
  readonly property string monitorGlyphWidgetSource: monitorAssetSource("MonitorGlyph.qml")
  readonly property string monitorWorkspaceWidgetSource: monitorAssetSource("Workspaces.qml")
  readonly property string monitorSettingsWidgetSource: monitorAssetSource("SettingsButton.qml")

  function connectedMonitorNames() {
    var names = []
    var screens = Quickshell.screens || []
    for (var i = 0; i < screens.length; i++) {
      var name = String(screens[i].name || "")
      if (name && names.indexOf(name) < 0) names.push(name)
    }
    return names
  }

  function monitorAssetSource(name) {
    return monitorAssetDir ? Util.fileUrl(monitorAssetDir + "/" + name) : ""
  }

  function copyEntry(entry) {
    if (typeof entry === "string") return { id: entry }
    try { return JSON.parse(JSON.stringify(entry)) } catch (e) { return { id: entryId(entry) } }
  }

  function configuredEntry(id) {
    var regions = ["left", "center", "right"]
    for (var r = 0; r < regions.length; r++) {
      var entries = layoutConfig && Array.isArray(layoutConfig[regions[r]]) ? layoutConfig[regions[r]] : []
      for (var i = 0; i < entries.length; i++)
        if (entryId(entries[i]) === id) return copyEntry(entries[i])
    }
    return { id: id }
  }

  function monitorGlyphEntry(glyph, label) {
    return {
      id: "patrickfanella.monitor-glyph",
      source: monitorGlyphWidgetSource,
      glyph: glyph,
      accessibleLabel: label
    }
  }

  function monitorWorkspaceEntry(workspaces) {
    var entry = configuredEntry("omarchy.workspaces")
    entry.id = "patrickfanella.monitor-workspaces"
    entry.source = monitorWorkspaceWidgetSource
    entry.workspaceIds = []
    entry.displayLabels = ({})
    for (var i = 0; i < workspaces.length; i++) {
      entry.workspaceIds.push(workspaces[i].id)
      entry.displayLabels[String(workspaces[i].id)] = workspaces[i].label
    }
    return entry
  }

  function fullWorkspaceEntry(sourceEntry) {
    var entry = copyEntry(sourceEntry)
    entry.source = monitorWorkspaceWidgetSource
    delete entry.workspaceIds
    delete entry.displayLabels
    return entry
  }

  function minimalLayout(screenName, output) {
    return {
      left: [monitorGlyphEntry(output.glyph, screenName + " monitor"), monitorWorkspaceEntry(output.workspaces)],
      center: [],
      right: []
    }
  }

  function fullLayout(screenName) {
    var result = { left: [], center: [], right: [] }
    var regions = ["left", "center", "right"]
    for (var r = 0; r < regions.length; r++) {
      var region = regions[r]
      var entries = layoutConfig && Array.isArray(layoutConfig[region]) ? layoutConfig[region] : []
      for (var i = 0; i < entries.length; i++) {
        result[region].push(entryId(entries[i]) === "omarchy.workspaces"
          ? fullWorkspaceEntry(entries[i])
          : copyEntry(entries[i]))
      }
    }
    if (isPrimaryScreen(screenName)) {
      result.right.push({
        id: "patrickfanella.monitor-bar.settings",
        source: monitorSettingsWidgetSource,
        syntheticSettings: true
      })
    }
    return result
  }

  function isPrimaryScreen(screenName) {
    return String(screenName || "") === monitorConfig.primary
  }

  function isFullScreen(screenName) {
    return MonitorBarModel.outputFor(monitorConfig, screenName).mode === "full"
  }

  function layoutFor(screenName) {
    if (!monitorAssetDir)
      return { mode: "hidden", layout: { left: [], center: [], right: [] }, anchor: "" }
    var name = String(screenName || "")
    var output = MonitorBarModel.outputFor(monitorConfig, name)
    if (output.mode === "full") return { mode: "full", layout: fullLayout(name), anchor: centerAnchor }
    if (output.mode === "minimal") return { mode: "minimal", layout: minimalLayout(name, output), anchor: "" }
    return { mode: "hidden", layout: { left: [], center: [], right: [] }, anchor: "" }
  }
  // --- end patrickfanella.monitor-bar transforms ---
""",
    )
    text = replace_exact(
        text,
        '      candidates.push({ slot: slot, screenName: slotScreenName(slot), opened: item.opened === true })\n',
        """      candidates.push({
        slot: slot,
        screenName: slotScreenName(slot),
        opened: item.opened === true,
        liveFull: isFullScreen(slotScreenName(slot))
      })
""",
    )
    text = replace_exact(
        text,
        """    var chosen = BarModel.pickPanelSlot(candidates, focusedScreenName())
""",
        """    var chosen = BarModel.pickPanelSlot(candidates, focusedScreenName(), monitorConfig.primary)
""",
    )
    text = replace_exact(
        text,
        """        id: slot.moduleName,
        section: slot.region,
""",
        """        id: slot.moduleName,
        screen: slotScreenName(slot),
        section: slot.region,
""",
    )
    text = replace_exact(
        text,
        """        if (!slot || slot.region !== change.region || slot.moduleName !== entryId(change.entry)) continue
""",
        """        if (!slot || !isFullScreen(slot.screenName) || slot.region !== change.region || slot.moduleName !== entryId(change.entry)) continue
""",
    )
    text = replace_exact(
        text,
        """  function layoutEntries(region) {
    var serial = barConfigSerial
    var entries = layoutConfig ? layoutConfig[region] : null
    return Array.isArray(entries) ? entries : []
  }
""",
        """  function layoutEntries(region, screenName) {
    var serial = barConfigSerial
    var spec = layoutFor(screenName)
    var entries = spec.layout ? spec.layout[region] : null
    return Array.isArray(entries) ? entries : []
  }
""",
    )
    text = replace_exact(
        text,
        """    var entries = layoutEntries(region)
    var slots = []
""",
        """    var screenName = window && window.screen ? String(window.screen.name || "") : monitorConfig.primary
    var entries = layoutEntries(region, screenName)
    var slots = []
""",
    )
    text = replace_exact(
        text,
        """        if (window && !sameWindow(slotWindow(slot), window)) continue
        var item = slot.activeItem
""",
        """        if (window && !sameWindow(slotWindow(slot), window)) continue
        if (!window && slotScreenName(slot) !== screenName) continue
        var item = slot.activeItem
""",
    )
    text = replace_exact(
        text,
        """  onBarConfigChanged: applyBarConfig()

  function layoutEntries""",
        """  onBarConfigChanged: applyBarConfig()
  onShellChanged: applyBarConfig()
  onManifestChanged: {
    applyBarConfig()
    barConfigSerial++
  }

  Connections {
    target: Quickshell
    function onScreensChanged() { root.applyBarConfig() }
  }

  Connections {
    target: root.shell
    ignoreUnknownSignals: true
    function onShellConfigChanged() { root.applyBarConfig() }
  }

  function layoutEntries""",
    )
    text = replace_exact(
        text,
        """  function dropBarModule(source, toRegion, beforeName) {
    if (!source || !source.region || !source.moduleName || !toRegion) return false
""",
        """  function dropBarModule(source, toRegion, beforeName) {
    if (!source || !isPrimaryScreen(slotScreenName(source)) || !source.region || !source.moduleName || !toRegion) return false
""",
    )
    text = replace_exact(
        text,
        """  function nextVisibleModuleName(region, afterName, sourceSlot) {
    var entries = layoutEntries(region)
""",
        """  function nextVisibleModuleName(region, afterName, sourceSlot) {
    var entries = layoutEntries(region, slotScreenName(sourceSlot))
""",
    )
    text = replace_exact(
        text,
        """  component BarPanel: PanelWindow {
    id: barWindow
""",
        """  component BarPanel: PanelWindow {
    id: barWindow
    readonly property string screenName: barWindow.screen ? String(barWindow.screen.name || "") : ""
    readonly property var monitorSpec: root.layoutFor(screenName)
""",
    )
    text = replace_exact(
        text,
        """    visible: !remapGuard.remapping
    exclusionMode: root.barHidden ? ExclusionMode.Ignore : ExclusionMode.Auto
""",
        """    visible: monitorSpec.mode !== "hidden" && !remapGuard.remapping
    exclusionMode: root.barHidden || monitorSpec.mode === "hidden" ? ExclusionMode.Ignore : ExclusionMode.Auto
""",
    )
    text = replace_exact(
        text,
        '    WlrLayershell.layer: WlrLayer.Top\n',
        """    WlrLayershell.layer: WlrLayer.Top
    // Bars must not take keyboard focus from the active application. Custom
    // buttons expose accessibility metadata, but keyboard use stays in the
    // focusable settings window or Hyprland's workspace shortcuts.
    WlrLayershell.keyboardFocus: WlrKeyboardFocus.None
""",
    )
    text = replace_exact(
        text,
        """      HoverHandler {
        onHoveredChanged: root.setBarHovered(hovered)
""",
        """      HoverHandler {
        enabled: root.isPrimaryScreen(barWindow.screenName)
        onHoveredChanged: root.setBarHovered(hovered)
""",
    )
    text = replace_exact(
        text,
        "CenterModules { anchors.fill: parent }",
        "CenterModules { screenName: barWindow.screenName; anchors.fill: parent }",
        count=2,
    )
    text = replace_exact(
        text,
        """        LeftModules {
          anchors""",
        """        LeftModules {
          screenName: barWindow.screenName
          anchors""",
        count=2,
    )
    text = replace_exact(
        text,
        """        RightModules {
          anchors""",
        """        RightModules {
          screenName: barWindow.screenName
          anchors""",
        count=2,
    )
    text = replace_exact(
        text,
        """  function findCenterAnchorEntry() {
    var entries = root.layoutEntries("center")
    var idx = root.entryIndex(entries, root.centerAnchor)
    return idx === -1 ? null : entries[idx]
  }

  component LeftModules: ModuleList {
    entries: root.layoutEntries("left")
    region: "left"
  }

  component RightModules: ModuleList {
    entries: root.layoutEntries("right")
    region: "right"
  }

  component CenterModules: Item {
    id: centerRoot

    property var entries: root.layoutEntries("center")
    readonly property bool hasAnchor: root.entryIndex(entries, root.centerAnchor) !== -1
    readonly property var anchorEntry: root.findCenterAnchorEntry()
""",
        """  function findCenterAnchorEntry(screenName) {
    var entries = root.layoutEntries("center", screenName)
    var anchor = root.layoutFor(screenName).anchor
    var idx = root.entryIndex(entries, anchor)
    return idx === -1 ? null : entries[idx]
  }

  component LeftModules: ModuleList {
    entries: root.layoutEntries("left", screenName)
    region: "left"
  }

  component RightModules: ModuleList {
    entries: root.layoutEntries("right", screenName)
    region: "right"
  }

  component CenterModules: Item {
    id: centerRoot

    property string screenName: ""
    property var entries: root.layoutEntries("center", screenName)
    readonly property string anchor: root.layoutFor(screenName).anchor
    readonly property bool hasAnchor: root.entryIndex(entries, anchor) !== -1
    readonly property var anchorEntry: root.findCenterAnchorEntry(screenName)
""",
    )
    text = replace_exact(text, "root.centerAnchor)", "centerRoot.anchor)", count=4)
    text = replace_exact(
        text,
        "CenterGestureArea { anchors.fill: parent }",
        "CenterGestureArea { screenName: centerRoot.screenName; anchors.fill: parent }",
        count=2,
    )
    text = replace_exact(
        text,
        """        HoverHandler {
          onHoveredChanged: root.setCenterSectionHovered(hovered)
""",
        """        HoverHandler {
          enabled: root.isPrimaryScreen(centerRoot.screenName)
          onHoveredChanged: root.setCenterSectionHovered(hovered)
""",
        count=2,
    )
    center_start = text.index("  component CenterModules: Item {")
    center_end = text.index("  component CenterGestureArea: MouseArea {", center_start)
    center = text[center_start:center_end]
    center = replace_exact(
        center,
        '          region: "center"\n',
        '          region: "center"\n          screenName: centerRoot.screenName\n',
        count=8,
    )
    text = text[:center_start] + center + text[center_end:]
    text = replace_exact(
        text,
        """  component CenterGestureArea: MouseArea {
    id: gestureArea

""",
        """  component CenterGestureArea: MouseArea {
    id: gestureArea

    property string screenName: ""
""",
    )
    text = replace_exact(
        text,
        """    acceptedButtons: Qt.LeftButton
    cursorShape:""",
        """    acceptedButtons: Qt.LeftButton
    enabled: root.isPrimaryScreen(screenName)
    cursorShape:""",
    )
    text = replace_exact(
        text,
        """    property var entries: []
    property string region: ""

    visible:""",
        """    property var entries: []
    property string region: ""
    property string screenName: ""

    visible:""",
    )
    text = replace_exact(
        text,
        """            entry: modelData
            region: moduleListRoot.region
""",
        """            entry: modelData
            region: moduleListRoot.region
            screenName: moduleListRoot.screenName
""",
        count=2,
    )
    text = replace_exact(
        text,
        """    required property var entry
    property string region: ""
    readonly property string moduleName:""",
        """    required property var entry
    property string region: ""
    property string screenName: ""
    readonly property string moduleName:""",
    )
    text = replace_exact(
        text,
        """      var w = root.barWidgetRegistry.widgets
      if (customType) return null
""",
        """      var w = root.barWidgetRegistry && root.barWidgetRegistry.widgets ? root.barWidgetRegistry.widgets : ({})
      if (customType) return null
""",
    )
    text = replace_exact(
        text,
        """      readonly property bool canReorder: root.shell && typeof root.shell.mutateShellConfig === "function"
""",
        """      readonly property bool canReorder: !(entry && entry.syntheticSettings) && root.isPrimaryScreen(slot.screenName) && root.shell && typeof root.shell.mutateShellConfig === "function"
""",
    )
    text = replace_exact(
        text,
        """      if ("settings" in target) target.settings = moduleSettings
    }
""",
        """      if ("settings" in target) target.settings = moduleSettings
      if ("screenName" in target) target.screenName = slot.screenName
    }
""",
    )
    return GENERATED_MARKER + text


def transform_model(source: str) -> str:
    text = replace_exact(
        source,
        """// An open copy wins first: hide and toggle have to reach the panel the user
// can actually see, wherever it was opened from. Otherwise the focused
// monitor's copy wins, so a summon lands where the user is working instead of
// on whichever output registered its slot first. Neither narrowing applies on
// a single monitor, or when the focused output has no bar of its own.
""",
        """// An open copy wins first: hide and toggle have to reach the panel the user
// can actually see. Otherwise route among live Full bars: focused output,
// connected configured primary, then any remaining Full output.
""",
    )
    return GENERATED_MARKER + replace_exact(
        text,
        """function pickPanelSlot(candidates, focusedScreen) {
  var rows = Array.isArray(candidates) ? candidates : []
  var pool = rows.filter(function(row) { return row && row.opened === true })
  if (pool.length === 0) pool = rows.filter(function(row) { return !!row })

  var focused = String(focusedScreen || "")
  if (focused) {
    var onFocused = pool.filter(function(row) { return row.screenName === focused })
    if (onFocused.length > 0) pool = onFocused
  }

  return pickDrawnSlot(pool.map(function(row) { return row.slot }))
}
""",
        """function pickPanelSlot(candidates, focusedScreen, primaryScreen) {
  var rows = Array.isArray(candidates) ? candidates.filter(function(row) { return !!row }) : []
  var opened = rows.filter(function(row) { return row.opened === true })
  if (opened.length > 0)
    return pickDrawnSlot(opened.map(function(row) { return row.slot }))

  var full = rows.filter(function(row) { return row.liveFull === true })
  var focused = String(focusedScreen || "")
  var onFocused = full.filter(function(row) { return row.screenName === focused })
  if (onFocused.length > 0)
    return pickDrawnSlot(onFocused.map(function(row) { return row.slot }))

  var primary = String(primaryScreen || "")
  var onPrimary = full.filter(function(row) { return row.screenName === primary })
  if (onPrimary.length > 0)
    return pickDrawnSlot(onPrimary.map(function(row) { return row.slot }))

  return pickDrawnSlot(full.map(function(row) { return row.slot }))
}
""",
    )


def load_upstream(name: str, upstream_dir: Path | None = None) -> str:
    path = (UPSTREAM_DIR if upstream_dir is None else upstream_dir) / name
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != EXPECTED_SHA256[name]:
        raise RuntimeError(
            f"{path} changed: expected sha256 {EXPECTED_SHA256[name]}, got {digest}"
        )
    return data.decode("utf-8")


def generated_files(upstream_dir: Path | None = None) -> dict[str, str]:
    return {
        "Bar.qml": transform_bar(load_upstream("Bar.qml", upstream_dir)),
        "BarModel.js": transform_model(load_upstream("BarModel.js", upstream_dir)),
    }


def staged_file(path: Path, data: bytes, mode: int) -> str:
    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "wb") as temporary:
            temporary.write(data)
            temporary.flush()
            os.fsync(temporary.fileno())
        return temporary_name
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def replace_generated(outputs: dict[str, str]) -> None:
    changed: dict[Path, bytes] = {}
    for name, content in outputs.items():
        if not content.startswith(GENERATED_MARKER):
            raise RuntimeError(f"generated marker missing from {name}")
        data = content.encode("utf-8")
        destination = PLUGIN_DIR / name
        if not destination.exists() or destination.read_bytes() != data:
            changed[destination] = data
    if not changed:
        return

    originals: dict[Path, tuple[bytes, int] | None] = {}
    staged: dict[Path, str] = {}
    replaced: list[Path] = []
    try:
        for destination, data in changed.items():
            if destination.exists():
                originals[destination] = (
                    destination.read_bytes(),
                    stat.S_IMODE(destination.stat().st_mode),
                )
            else:
                originals[destination] = None
            original = originals[destination]
            mode = original[1] if original is not None else 0o644
            staged[destination] = staged_file(destination, data, mode)

        for destination, temporary_name in staged.items():
            os.replace(temporary_name, destination)
            replaced.append(destination)
        directory_fd = os.open(PLUGIN_DIR, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except BaseException:
        for destination in reversed(replaced):
            original = originals[destination]
            if original is None:
                destination.unlink(missing_ok=True)
            else:
                rollback = staged_file(destination, original[0], original[1])
                os.replace(rollback, destination)
        raise
    finally:
        for temporary_name in staged.values():
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument(
        "--upstream-dir",
        type=Path,
        default=None,
        help=f"read pinned stock sources from PATH (default: {UPSTREAM_DIR})",
        metavar="PATH",
    )
    args = parser.parse_args()

    try:
        outputs = generated_files(args.upstream_dir)
        if args.check:
            stale = []
            for name, content in outputs.items():
                destination = PLUGIN_DIR / name
                if not destination.exists() or destination.read_text(encoding="utf-8") != content:
                    stale.append(name)
            if stale:
                raise RuntimeError("stale generated file(s): " + ", ".join(stale))
        else:
            replace_generated(outputs)
    except (OSError, RuntimeError, UnicodeError) as error:
        print(f"sync_stock_bar.py: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
